# Generated by Django 3.1.4 on 2021-01-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='emp_name',
            new_name='employee',
        ),
    ]
