# Generated by Django 3.1.4 on 2021-02-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remainingday',
            field=models.IntegerField(null=True),
        ),
    ]
