# Generated by Django 3.1.5 on 2021-02-05 17:28

from django.db import migrations

def link_department(apps, schema_editor):
    User = apps.get_model('login', 'User')
    Department = apps.get_model('login', 'Department')
    for user in User.objects.all():
        dept, created = Department.objects.get_or_create(dept_name=user.department)
        user.department_link = dept
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(link_department)
    ]
