# Generated by Django 3.1.4 on 2020-12-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_registeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='phone_numver',
            new_name='phone_number',
        ),
    ]
