# Generated by Django 3.1.5 on 2021-02-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_tansfers_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
