# Generated by Django 3.1.4 on 2020-12-27 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
    ]
