# Generated by Django 3.1.4 on 2020-12-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_salary_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
