# Generated by Django 3.1.4 on 2021-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210106_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='abc', max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='IT', max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='abc', max_length=225),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='abc', max_length=225),
        ),
    ]
