# Generated by Django 3.1.5 on 2021-02-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_link',
            new_name='department',
        ),
    ]
