# Generated by Django 3.1.4 on 2021-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210112_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_status',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='leave',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
