# Generated by Django 3.1.4 on 2020-12-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_leave_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
