# Generated by Django 3.1.4 on 2021-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210106_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
