# Generated by Django 3.1.4 on 2020-12-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201227_0820'),
        ('login', '0004_attendance'),
    ]

    operations = [
    ]
