# Generated by Django 3.1.4 on 2021-01-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_notapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_notverified',
            field=models.BooleanField(default=False),
        ),
    ]
