# Generated by Django 3.1.4 on 2020-12-27 07:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201227_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
