# Generated by Django 3.1.4 on 2021-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210117_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_notapproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_notverified',
            field=models.BooleanField(default=True),
        ),
    ]
