# Generated by Django 3.1.4 on 2020-12-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201227_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='emp_name',
        ),
    ]
