# Generated by Django 3.1.5 on 2021-01-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210117_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.department'),
        ),
    ]
