# Generated by Django 3.1.4 on 2020-12-27 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201227_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='choices',
            field=models.CharField(choices=[('CI', 'checkin'), ('CO', 'checkout')], default='checkin', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
