# Generated by Django 3.1.4 on 2020-12-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_leave_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='file',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
