# Generated by Django 3.1.5 on 2021-01-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_salary_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
