# Generated by Django 3.1.4 on 2020-12-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201227_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.department'),
        ),
    ]
