# Generated by Django 3.1.4 on 2020-12-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_salary_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='emp_id',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='users',
        ),
    ]
