# Generated by Django 3.1.5 on 2021-01-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210117_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='choices',
        ),
    ]
