# Generated by Django 3.1.4 on 2020-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201227_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
