# Generated by Django 3.1.5 on 2021-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_attendance_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checkout',
        ),
        migrations.AddField(
            model_name='attendance',
            name='choices',
            field=models.CharField(choices=[('CI', 'checkin'), ('CO', 'checkout')], default='checkin', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
