# Generated by Django 3.1.4 on 2020-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20201227_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='file',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
