# Generated by Django 3.1.4 on 2020-12-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_20201227_1609'),
        ('login', '0014_auto_20201227_1540'),
    ]

    operations = [
    ]
