# Generated by Django 3.1.4 on 2020-12-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20201227_1540'),
        ('login', '0011_auto_20201227_2202'),
    ]

    operations = [
    ]
