# Generated by Django 3.1.4 on 2020-12-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20201228_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='userfile',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
