# Generated by Django 3.1.4 on 2020-12-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20201228_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='department',
            field=models.ForeignKey(max_length=225, on_delete=django.db.models.deletion.CASCADE, to='login.department'),
        ),
    ]
