# Generated by Django 3.1.4 on 2020-12-28 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20201228_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
