# Generated by Django 3.1.4 on 2020-12-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20201228_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
