# Generated by Django 3.1.4 on 2020-12-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20201229_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
