# Generated by Django 3.1.4 on 2021-01-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210105_1352'),
        ('login', '0020_auto_20201229_2211'),
    ]

    operations = [
    ]
