# Generated by Django 3.1.4 on 2020-12-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20201229_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
